// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "Series y Peliculas Colombianas", " ", "Series y peliculas colombianas completas audio latino.");
   this[database_length++] = new SearchPage("Series66.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("lady.html", "Lady, la vendedora de rosas", " ", "Lady es una niña de diez años que roba rosas para venderlas, poder comer y juntar el pago que arriendan en un inquilinato junto con su madre Fátima, una mujer desgastada por los golpes de la vida  y su hermano Didier, de ocho años. El gran amigo de Lady es Alex, un joven algo tímido, quien es hijo de Arnulfo, hermano de Elmer, dueño del inquilinato y quien fue abandonado por su mujer en el altar. Fátima y Lady se disponen a vender en los semáforos las rosas que han robado en el barrio El Poblado, con el fin de pagar lo que le adeudan a don Elmer...    Sofía Soto, una abogada defensora de menores muy ceñida a las normas, está empeñada en separar a Fátima de su hija por ponerla a trabajar de vendedora ambulante, creyendo que así ayudará a rescatar a una niña más en situación de abandono. Con el tiempo, Lady termina en un orfanato en el municipio de La Estrella, cerca de Medellín. Ella hace lo que sea por reencontrarse con su madre, intenta fugarse varias veces, pero es localizada antes de cumplir con su objetivo. Lady les da guerra a las religiosas donde se encuentra internada, hasta el punto de llegar a recibir fuertes castigos.    El tiempo pasa y Fátima, agobiada por la pérdida de Lady, se sumerge cada vez más en el alcohol. Guarda la esperanza que cuando se encuentre con su hija ella sea una mejor persona. La joven a sus catorce años ha aprendido todo sobre valores, pero poco sobre comportamiento. Mientras tanto, Marco García, un director de cine que anda en la búsqueda de actrices, prepara su nueva película  un proyecto sobre niñas que deambulan por la ciudad vendiendo rosas.");
   this[database_length++] = new SearchPage("introlady.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("ladyt1-o1.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("guaca.html", "Lady, la vendedora de rosas", " ", "Lady es una niña de diez años que roba rosas para venderlas, poder comer y juntar el pago que arriendan en un inquilinato junto con su madre Fátima, una mujer desgastada por los golpes de la vida  y su hermano Didier, de ocho años. El gran amigo de Lady es Alex, un joven algo tímido, quien es hijo de Arnulfo, hermano de Elmer, dueño del inquilinato y quien fue abandonado por su mujer en el altar. Fátima y Lady se disponen a vender en los semáforos las rosas que han robado en el barrio El Poblado, con el fin de pagar lo que le adeudan a don Elmer...    Sofía Soto, una abogada defensora de menores muy ceñida a las normas, está empeñada en separar a Fátima de su hija por ponerla a trabajar de vendedora ambulante, creyendo que así ayudará a rescatar a una niña más en situación de abandono. Con el tiempo, Lady termina en un orfanato en el municipio de La Estrella, cerca de Medellín. Ella hace lo que sea por reencontrarse con su madre, intenta fugarse varias veces, pero es localizada antes de cumplir con su objetivo. Lady les da guerra a las religiosas donde se encuentra internada, hasta el punto de llegar a recibir fuertes castigos.    El tiempo pasa y Fátima, agobiada por la pérdida de Lady, se sumerge cada vez más en el alcohol. Guarda la esperanza que cuando se encuentre con su hija ella sea una mejor persona. La joven a sus catorce años ha aprendido todo sobre valores, pero poco sobre comportamiento. Mientras tanto, Marco García, un director de cine que anda en la búsqueda de actrices, prepara su nueva película  un proyecto sobre niñas que deambulan por la ciudad vendiendo rosas.");
   this[database_length++] = new SearchPage("guacat1.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("muñecas.html", "Lady, la vendedora de rosas", " ", "Lady es una niña de diez años que roba rosas para venderlas, poder comer y juntar el pago que arriendan en un inquilinato junto con su madre Fátima, una mujer desgastada por los golpes de la vida  y su hermano Didier, de ocho años. El gran amigo de Lady es Alex, un joven algo tímido, quien es hijo de Arnulfo, hermano de Elmer, dueño del inquilinato y quien fue abandonado por su mujer en el altar. Fátima y Lady se disponen a vender en los semáforos las rosas que han robado en el barrio El Poblado, con el fin de pagar lo que le adeudan a don Elmer...    Sofía Soto, una abogada defensora de menores muy ceñida a las normas, está empeñada en separar a Fátima de su hija por ponerla a trabajar de vendedora ambulante, creyendo que así ayudará a rescatar a una niña más en situación de abandono. Con el tiempo, Lady termina en un orfanato en el municipio de La Estrella, cerca de Medellín. Ella hace lo que sea por reencontrarse con su madre, intenta fugarse varias veces, pero es localizada antes de cumplir con su objetivo. Lady les da guerra a las religiosas donde se encuentra internada, hasta el punto de llegar a recibir fuertes castigos.    El tiempo pasa y Fátima, agobiada por la pérdida de Lady, se sumerge cada vez más en el alcohol. Guarda la esperanza que cuando se encuentre con su hija ella sea una mejor persona. La joven a sus catorce años ha aprendido todo sobre valores, pero poco sobre comportamiento. Mientras tanto, Marco García, un director de cine que anda en la búsqueda de actrices, prepara su nueva película  un proyecto sobre niñas que deambulan por la ciudad vendiendo rosas.");
   this[database_length++] = new SearchPage("muñecat1.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("cartel.html", "Lady, la vendedora de rosas", " ", "Lady es una niña de diez años que roba rosas para venderlas, poder comer y juntar el pago que arriendan en un inquilinato junto con su madre Fátima, una mujer desgastada por los golpes de la vida  y su hermano Didier, de ocho años. El gran amigo de Lady es Alex, un joven algo tímido, quien es hijo de Arnulfo, hermano de Elmer, dueño del inquilinato y quien fue abandonado por su mujer en el altar. Fátima y Lady se disponen a vender en los semáforos las rosas que han robado en el barrio El Poblado, con el fin de pagar lo que le adeudan a don Elmer...    Sofía Soto, una abogada defensora de menores muy ceñida a las normas, está empeñada en separar a Fátima de su hija por ponerla a trabajar de vendedora ambulante, creyendo que así ayudará a rescatar a una niña más en situación de abandono. Con el tiempo, Lady termina en un orfanato en el municipio de La Estrella, cerca de Medellín. Ella hace lo que sea por reencontrarse con su madre, intenta fugarse varias veces, pero es localizada antes de cumplir con su objetivo. Lady les da guerra a las religiosas donde se encuentra internada, hasta el punto de llegar a recibir fuertes castigos.    El tiempo pasa y Fátima, agobiada por la pérdida de Lady, se sumerge cada vez más en el alcohol. Guarda la esperanza que cuando se encuentre con su hija ella sea una mejor persona. La joven a sus catorce años ha aprendido todo sobre valores, pero poco sobre comportamiento. Mientras tanto, Marco García, un director de cine que anda en la búsqueda de actrices, prepara su nueva película  un proyecto sobre niñas que deambulan por la ciudad vendiendo rosas.");
   this[database_length++] = new SearchPage("cartelt1.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("hasta.html", "Lady, la vendedora de rosas", " ", "Lady es una niña de diez años que roba rosas para venderlas, poder comer y juntar el pago que arriendan en un inquilinato junto con su madre Fátima, una mujer desgastada por los golpes de la vida  y su hermano Didier, de ocho años. El gran amigo de Lady es Alex, un joven algo tímido, quien es hijo de Arnulfo, hermano de Elmer, dueño del inquilinato y quien fue abandonado por su mujer en el altar. Fátima y Lady se disponen a vender en los semáforos las rosas que han robado en el barrio El Poblado, con el fin de pagar lo que le adeudan a don Elmer...    Sofía Soto, una abogada defensora de menores muy ceñida a las normas, está empeñada en separar a Fátima de su hija por ponerla a trabajar de vendedora ambulante, creyendo que así ayudará a rescatar a una niña más en situación de abandono. Con el tiempo, Lady termina en un orfanato en el municipio de La Estrella, cerca de Medellín. Ella hace lo que sea por reencontrarse con su madre, intenta fugarse varias veces, pero es localizada antes de cumplir con su objetivo. Lady les da guerra a las religiosas donde se encuentra internada, hasta el punto de llegar a recibir fuertes castigos.    El tiempo pasa y Fátima, agobiada por la pérdida de Lady, se sumerge cada vez más en el alcohol. Guarda la esperanza que cuando se encuentre con su hija ella sea una mejor persona. La joven a sus catorce años ha aprendido todo sobre valores, pero poco sobre comportamiento. Mientras tanto, Marco García, un director de cine que anda en la búsqueda de actrices, prepara su nueva película  un proyecto sobre niñas que deambulan por la ciudad vendiendo rosas.");
   this[database_length++] = new SearchPage("hastat1.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("Peliculas66.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("categorias.html", "Untitled Page", "   ", "");
   this[database_length++] = new SearchPage("Peliculas.html", "Untitled Page", "   ", "");
   this[database_length++] = new SearchPage("Series.html", "Untitled Page", "   ", "");
   this[database_length++] = new SearchPage("Todas.html", "Untitled Page", "   ", "");
   this[database_length++] = new SearchPage("favoritos.html", "Untitled Page", "     ", "");
   this[database_length++] = new SearchPage("buscar.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("master.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("Temporadasalasdy2.1.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("savecap.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("..html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("...html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("politica.html", "Untitled Page", "   ", "");
   this[database_length++] = new SearchPage("aviso.html", "Untitled Page", "   ", "");
   this[database_length++] = new SearchPage("page1.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("page2.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("page3.html", "Untitled Page", " ", "");
   return this;
}
